sonar.organization=computer-vision-mai
sonar.projectKey=Computer-Vision-MAI_ForensicsApp
sonar.projectName=ForensicsApp

sonar.sources=forensics_app
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml